export const  GET_PRODUCTS = "GET_PRODUCTS";

export const SET_SPECIFIC_PRODUCT= "SET_SPECIFIC_PRODUCT";
export const ISLOADING = "ISLOADING";
export const ISERROR = "ISERROR";

export const GET_AIRDROPS = "GET_AIRDROPS";
export const GET_WATCHES = "GET_WATCHES";
export const GET_HEADPHONES = "GET_HEADPHONES";
export const GET_SPEAKERS = "GET_SPEAKERS"
export const GET_SOUND_BARS = "GET_SOUND_BARS";
export const GET_PARTY_SPEAKERS = "GET_PARTY_SPEAKERS"